language: bash
addons:
  ssh_known_hosts: 172.24.113.91
before_deploy:
- openssl aes-256-cbc -K $encrypted_6084f853fea8_key -iv $encrypted_6084f853fea8_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: ssh liyiwen@172.24.113.91 << EOF ls echo "Hello World!" EOF
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_6084f853fea8_key -iv $encrypted_6084f853fea8_iv
  -in deploy_rsa.enc -out deploy_rsa -d
