language: bash
addons:
  ssh_known_hosts: 192.168.0.20
before_deploy:
- openssl aes-256-cbc -K $encrypted_6084f853fea8_key -iv $encrypted_6084f853fea8_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- echo "*** before deploy ***"
deploy:
  provider: script
  skip_cleanup: true
  script: ssh -i "Yiwen-Ubuntu.pem" ec2-user@ec2-54-224-101-104.compute-1.amazonaws.com << EOF
          ls
          EOF
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_6084f853fea8_key -iv $encrypted_6084f853fea8_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- echo "*** before install ***"
