language: bash
addons:
  ssh_known_hosts: 172.24.113.91

before_deploy:
- openssl aes-256-cbc -K $encrypted_<...>_key -iv $encrypted_<...>_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: 
    ssh liyiwen@173.24.113.91 << EOF 
        ls
        echo "Hello World!"
    EOF
  on:
    branch: master
